FROM eiel/haskell-stack
MAINTAINER Tomohiko Himura <eiel.hal@gmail.com>

ENV STACK_RESOLVER lts-3.11

RUN stack new setup simple --resolver $STACK_RESOLVER && \
      cd setup && \
      stack setup && \
      echo "    , warp" >> setup.cabal && \
      stack build && \
      cd .. && \
      rm -rf setup
